#!/bin/sh
for age in 8 9 10 11 12 13 14 15 16 17
	do
	for model in 1 2 3 4
		do
		for shift in -0.25 -0.2 -0.15 -0.1 -0.05 0 0.05 0.1 0.15 0.2 0.25
			do
			wwwask age 
			model 
			shift
			cat wwwask.200 >> newchem.data
			cat wwwask.lbars >> newlbars.data
			done
		done 
	done